### ISSUE TITLE
site is down 

### ISSUE THREAD

**Issue by AMANUELAB** [thelevicole/youtube-to-html5-loader#24] opened 2022-04-02 05:54 UTC
https://yt2html5.com

 Error 502 Ray ID: 6f574c041be959e3 • 2022-04-02 05:52:10 UTC
Bad gateway

yt2html5.com
Host
Error

**Comment by AMANUELAB** [comment] 2022-04-04 22:52
it would be better if you provide a code of https://yt2html5.com/

**Comment by KamelHtira** [comment] 2022-05-11 05:25
The site get down every few days.
Is there any solution ?

**Comment by AMANUELAB** [comment] 2022-05-12 03:26
i think this thing is not gone work anymore

**Comment by thelevicole** [comment] 2022-07-21 16:53
Duplicate of #27

**Closed by thelevicole** 2022-07-21 16:53 UTC
