### ISSUE TITLE
i think this thing is not gone work anymore 

### ISSUE THREAD

**Issue by AMANUELAB** [thelevicole/youtube-to-html5-loader#26] opened 2022-05-12 03:26 UTC

**Comment by KamelHtira** [comment] 2022-05-12 05:23
Are you using the library API, or you downloaded and used locally ?
Because i think the problem from the API.

**Comment by KamelHtira** [comment] 2022-05-12 05:41
@thelevicole are you changing API server ?

**Comment by thelevicole** [comment] 2022-07-21 16:53
Duplicate of #27

**Closed by thelevicole** 2022-07-21 16:53 UTC
